export const user =[
    {
        id: 1,
        name: {
            firstname: "Melrose",
            lastname: "Valiente",
        },
        course: "BS INFORMATION TECHNOLOGY",
        year: 3,
        section: "A",
        userType: "Student",
        username: "meloy2002",
        password: "meloy0512",
    },
    {
        id: 2,
        name: {
            firstname: "jea norene",
            lastname: "oring",
        },
        course: "BS INFORMATION TECHNOLOGY",
        year: 3,
        section: "A",
        userType: "Student",
        username: "jea",
        password: "norene123",
    },
    {
        id: 3,
        name: {
            firstname: "ma.luisa",
            lastname: "tinaja",
        },
        course: "BS COMPUTER ENGINEERING",
        year: 3,
        section: "A",
        userType: "Student",
        username: "eyay",
        password: "luisa123",
    },
    {
        id: 4,
        name: {
            firstname: "sherwen",
            lastname: "lahoy",
        },
        course: "BS ACCOUNTANCY",
        year: '3',
        section: "A",
        userType: "Student",
        username: "sherwen",
        password: "sher123",
    },
    {
        id: 5,
        name: {
            firstname: "Melrose",
            lastname: "Valiente",
        },
        course: "BS CRIMINOLOGY",
        year: 3,
        section: "A",
        userType: "Student",
        username: "melmel12",
        password: "melbourne",
    },
    {
        id: 6,
        name: {
            firstname: "Jerry",
            lastname: "Ale",
        },
        course: "BS INFORMATION TECHNOLOGY",
        year: '',
        section: "",
        userType: "Teacher",
        username: "@ALEJERRY",
        password: "ALE_JERRY",
    },
    {
        id: 7,
        name: {
            firstname: "lovelyn",
            lastname: "magsino",
        },
        course: "BS CRIMINOLOGY",
        year: '3',
        section: "B",
        userType: "Student",
        username: "lovelove",
        password: "lovelyn123",
    },
    {
        id: 8,
        name: {
            firstname: "daisy",
            lastname: "eusalan",
        },
        course: "BSIT- FBSM",
        year: 3,
        section: "B",
        userType: "Student",
        username: "diane",
        password: "eusalan123",
    },
    {
        id: 9,
        name: {
            firstname: "Mylene",
            lastname: "monteron",
        },
        course: "BS CIVIL ENGINEERING",
        year: 3,
        section: "A",
        userType: "Student",
        username: "maymay",
        password: "may123",
    },
    {
        id: 10,
        name: {
            firstname: "cherrie",
            lastname: "valiente",
        },
        course: "BS Information Technology",
        year: '',
        section: " ",
        userType: "Teacher",
        username: "maam_cher",
        password: "mae123",
    },
    {
        id: 11,
        name: {
            firstname: "alona",
            lastname: "valiente",
        },
        course: "BS COMPUTER SCIENCE",
        year: '',
        section: " ",
        userType: "Teacher",
        username: "maam_alona",
        password: "alona123",
    },
    {
        id: 12,
        name: {
            firstname: "ivy",
            lastname: "asilo",
        },
        course: "BS ACCOUNTANCY",
        year: '',
        section: " ",
        userType: "Teacher",
        username: "@maam_ivy",
        password: "jov123",
    },
    {
        id: 13,
        name: {
            firstname: "Ashley",
            lastname: "Ortega",
        },
        course: "BS CRIMINOLOGY",
        year: '4',
        section: "C ",
        userType: "Student",
        username: "ortega_ashley",
        password: "ash4376",
    },
    {
        id: 14,
        name: {
            firstname: "Jocelyn",
            lastname: "Jala",
        },
        course: "BS ELECTRONIC TECHNOLOGY",
        year: '',
        section: " ",
        userType: "Teacher",
        username: "mjala_jocelyn",
        password: "dmaam@JALA",
    },
    {
        id: 15,
        name: {
            firstname: "Natasha",
            lastname: "Toring",
        },
        course: "BS OFFICE ADMINISTRATION",
        year: '',
        section: " ",
        userType: "Teacher",
        username: "maam_tasha",
        password: "dTNatasha348975",
    },
    {
        id: 16,
        name: {
            firstname: "asha",
            lastname: "oring",
        },
        course: "BS OFFICE ADMINISTRATION",
        year: '1',
        section: "D",
        userType: "Student",
        username: "asha",
        password: "O_asha3485",
    },
    {
        id: 17,
        name: {
            firstname: "crisia",
            lastname: "0ng",
        },
        course: "BS INDUSTRIAL TECHNOLOGY",
        year: '2',
        section: "C",
        userType: "Student",
        username: "akasiang",
        password: "S348975",
    },
    {
        id: 18,
        name: {
            firstname: "Victoria",
            lastname: "Toring",
        },
        course: "BS PSYCHOLOGY",
        year: '',
        section: " ",
        userType: "Teacher",
        username: "maam_VIC",
        password: "dTORING5",
    },
    {
        id: 19,
        name: {
            firstname: "LUISA",
            lastname: "ORIGENES",
        },
        course: "BS PSYCHOLOGY",
        year: '4',
        section: "B ",
        userType: "Student",
        username: "luisa_origenes",
        password: "348975",
    },
    {
        id: 20,
        name: {
            firstname: "nikka jean",
            lastname: "torreon",
        },
        course: "BS TOURISM MANAGEMENT",
        year: '2',
        section: "A",
        userType: "Student",
        username: "@atshi_jean",
        password: "dTAYLORS635",
    },
];